config/urls.py
from django.urls import path, include, re_path
from .views import (PhotoListView,
                    PhotoCreateView,
                    PhotoDetailView,
                    PhotoUpdateView,
                    PhotoDeleteView)

app_name = 'photo'

urlpatterns = [
    path('photos/', PhotoListView.as_view(), name='list'),
    path('photos/create/', PhotoCreateView.as_view(), name='create'),
    path('photos/<int:pk>', PhotoDetailView.as_view(), name='detail'),
    path('photos/update/<int:pk>', PhotoUpdateView.as_view(), name='update'),
    path('photos/delete/<int:pk>', PhotoDeleteView.as_view(), name='delete')
]

djangoClassBasedView/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('config.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from .views import SignUpView, UserLoginView, UserLogoutView

# urls.py
app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
]

config/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import PhotoUser

CATEGORY = (
    ('Nature', 'Природа'),
    ('Animals', 'Животные'),
    ('Cities', 'Города'),
    ('Cars', 'Машины')
)


class Photo(models.Model):
    author = models.ForeignKey(PhotoUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/')  # для изображения
    name = models.CharField(max_length=255)  # для текста
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=255, choices=CATEGORY)


# (1) python manage.py makemigrations users
# (2) python manage.py migrate


# urls.py

users/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser,
                                        PermissionsMixin)


class PhotoUser(AbstractUser, PermissionsMixin):
    username = models.CharField(max_length=155, unique=True)
    email = models.EmailField()

config/forms.py
from django import forms
from .models import Photo


# forms.py
class PhotoCreationForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import PhotoUser


# forms.py
class UserForm(UserCreationForm):
    class Meta:
        model = PhotoUser
        fields = ['username', 'email']

config/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import (ListView,
                                  DeleteView,
                                  DetailView,
                                  UpdateView,
                                  CreateView, )
from .models import Photo
from .forms import PhotoCreationForm
from django.urls import reverse_lazy
from .filters import PhotoSearch


class PhotoListView(ListView):
    paginate_by = 5
    model = Photo
    template_name = 'list.html'
    context_object_name = 'photos'

    def get_queryset(self):
        queryset = super().get_queryset().order_by('created_at')
        self.filterset = PhotoSearch(
            self.request.GET,
            queryset=queryset
        )

        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['filter'] = self.filterset
        return context


class PhotoCreateView(CreateView):
    model = Photo
    template_name = 'create.html'
    success_url = reverse_lazy('photo:list')
    fields = ['name', 'image', 'category']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'detail.html'
    context_object_name = 'photo'


class PhotoUpdateView(UpdateView):
    model = Photo
    template_name = 'update.html'
    fields = '__all__'
    success_url = reverse_lazy('photo:list')


class PhotoDeleteView(DeleteView):
    model = Photo
    template_name = 'delete.html'
    context_object_name = 'photo'
    success_url = reverse_lazy('photo:list')

# git pull

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings
from .forms import UserForm


class SignUpView(CreateView):
    template_name = 'signup.html'
    form_class = UserForm
    success_url = reverse_lazy('photo:list')

    def form_valid(self, form):
        to_return = super().form_valid(form)
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1']
        )

        login(self.request, user)

        send_mail(
            subject="Успешная авторизация!",
            message="Вы успешно авторизовались на нашем сайте! "
                    "Добро пожаловать!",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.request.user.email],
            fail_silently=False
        )

        return to_return


class UserLoginView(LoginView):
    template_name = 'login.html'


class UserLogoutView(LogoutView):
    pass

templates/create.html
{% extends 'index.html' %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Add photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>
{% endblock body %}

templates/delete.html
{% extends 'index.html' %}

{% block body %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>:
      "<i>{{ photo.name }}</i>"
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock body %}

templates/detail.html
{% extends 'index.html' %}

{% block body %}
<div class="mx-auto">
  <h1 class="text-center">{{ photo.title }}</h1>
  <p class="text-center fw-light">Uploaded on: {{photo.created_at}}</p>
    <p class="text-center">
      <span><a href="{% url 'photo:update' photo.id %}" class="text-primary px-2">Update</a></span>
      <span><a href="{% url 'photo:delete' photo.id %}" class="text-danger px-2">Delete</a></span>
    </p>
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{photo.image.url}}" alt="" width="100%" />
  </div>
  <div class="col-md-4">
    <h4>More about this photo:</h4>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      <li><a class="btn btn-sm list-group-item list-group-item-primary">{{photo.category}}</a></li>
    </ul>
    <p>{{ photo.name }}</p>
  </div>
</div>

{% endblock body %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Photo Sharing app</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  </head>
  <body>
    {% include 'navbar.html' %}

    <div class="container mt-4">
    {% block body %}

    {% endblock body %}

    </div>

  </body>
</html>

templates/list.html
{% extends 'index.html' %}

{% block body %}

    <div class="p-5 container row">

    <div class="col-auto">
        <div class="col mb-2">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
            Поиск
        </button>
    </div>


<div class="col-auto" style="min-height: 0;">
  <div class="collapse collapse-horizontal show" id="collapseWidthExample">
    <div class="card card-body" style="width: 300px;">
      <form method="get">
          <div class="form-control m-2">
              <label for="{{ filter.form.id_for_name }}">Name subject:</label>

              <input type="text" name="name">
          </div>

          <div class="form-control m-2">
              <label for="{{ filter.form.id_for_name }}">Category:</label>

              <select name="category" id="id_category"></select>
          </div>

          <div class="col form-control m-2">
              <label for="{{ filter.form.id_for_name }}">Author:</label>
              {{ filter.form.author }}
          </div>
        <button class="m-2 btn btn-outline-primary" type="submit">Найти</button>
    </form>
    </div>
  </div>
</div>
    </div>





<div class="row container-fluid">
  {% for photo in photos %}
  <div class="card m-1 col-sm-3">
    <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
      <img src="{{ photo.image.url }}" class="rounded img-fluid" alt="{{ photo.title }}" />
        <p>{{ photo.name }}</p>
    </a>
  </div>
  {% empty %}
    No photos found.
  {% endfor %}
    <a href="{% url 'photo:create' %}" class="btn btn-info">
      Upload photo
    </a>
</div>


<nav class="mt-2" aria-label="Page navigation example">
  <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    Предыдующая</a>
            </li>
        {% endif %}

      {% for num_page in paginator.page_range %}
      	<li class="page-item">
            <a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
      {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая</a></li>
    {% endif %}
  </ul>
</nav>
    </div>


{% endblock body %}

templates/login.html
{% extends 'index.html' %}

{% block body %}

<main class="form-signin col-4 col-sm-4 col-lg-3 m-auto">
  <form action="" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating mb-2">
        <label for="id_username"></label>
        <input type="text" class="form-control" id="id_username" name="username" placeholder="name@example.com" required>
      <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
        <label for="id_password"></label>
        <input type="password" class="form-control" id="id_password" name="password" placeholder="Password" required>
      <label for="floatingPassword">Password</label>
    </div>
    <button class="btn btn-primary w-100 py-2 my-2" type="submit">Sign in</button>
  </form>
    {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Don't have an account?
      <a href="{% url 'user:signup' %}" class="text-primary ml-2">Create account</a>
    </p>
  </div>

</main>


{% endblock body %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarTogglerDemo02">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link active" href="#">Hi {{user.username}}</a>
            </li>

            <form method="post" action="{% url 'user:logout' %}">
            {% csrf_token %}
                <li class="nav-item">
                  <button class="btn btn-sm btn-info">Logout</button>
                </li>
            </form>

        {% else %}

            <li class="nav-item">
              <a href="{% url 'user:login' %}" class="btn btn-sm btn-outline-primary"
                >Sign In</a>
            </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/signup.html
{% extends 'index.html' %}
{% block body %}
    <div class="col mb-4">
    <h2 class="text-center">Welcome to the DjangoClassBasedView</h2>
    </div>
<div class="mx-auto col-4 col-sm-6 col-lg-4 border rounded p-4 ">
      <div class="form-group">
        <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Username</label>
        <input type="text" class="form-control" id="id_username" name="username" placeholder="zarpach...">
        <ul>
            {% for error in form.username.errors %}
              <li class="text-danger pt-2">{{ error }}</li>
            {% endfor %}
        </ul>
      </div>
      <div class="form-group">
        <label for="id_email">Email</label>
        <input type="email" class="form-control" id="id_email" name="email" placeholder="example@mail.com">
          <ul>
            {% for error in form.username.email %}
              <li class="text-danger px-4 pt-2">{{ error }}</li>
            {% endfor %}
        </ul>
      </div>
      <div class="form-group">
        <label for="id_password1">Password</label>
        <input type="password" class="form-control" id="id_password1" name="password1">
          <ul>
            {% for error in form.username.password1 %}
              <li class="text-danger px-4 pt-2">{{ error }}</li>
            {% endfor %}
        </ul>
      </div>
      <div class="form-group">
        <label for="id_password2">Confirm Password</label>
        <input type="password" class="form-control" id="id_password2" name="password2">
          <ul>
            {% for error in form.username.password2 %}
              <li class="text-danger px-4 pt-2">{{ error }}</li>
            {% endfor %}
        </ul>
      </div>
  <button type="submit" class="btn btn-primary w-100 mb-3">Create account</button>
</form>

  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Already Registered?
      <a href="{% url 'user:login' %}" class="text-primary ml-2"> Login </a>
    </p>
  </div>
</div>
{% endblock body %}

templates/update.html
{% extends 'index.html' %}


{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo.name}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock body %}